# Generated by Django 3.0.5 on 2020-04-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_post_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_address',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
