# Generated by Django 3.0.5 on 2020-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200427_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
